# Site
name: "Data Crafts"
title: "Data Crafts"
description: "Welcome to Data Crafts' blog."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ""
google_analytics: ''
disqus: ''
# mailchimp-list: ''
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  abdelkrim:
    name: Abdelkrim Hadjidj
    display_name: Abdelkrim
    gravatar: 22d66e5933a43f7422aff47bd2ef84e2
    email: abdelkrim.hadjidj@gmail.com
    web: https://www.datacrafts.fr/about
    twitter: https://twitter.com/ahadjidj
    description: "Data Streaming Specialist at Cloudera | Mentor | Speaker | Teacher | I write about distributed systems, solution engineering and craftmanship "
  
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub"
adsense-data-ad-slot: "13630"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
